# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore

    - id: build
      name: Build      
      run: dotnet build --no-restore

      # This will run the test step and collect data on results
    - id: test
      if: steps.build.outcome == 'success'
      name: Test
      run: dotnet test "PieShopHRM.Tests/PieShopHRM.Tests.csproj" --collect "XPlat Code Coverage" -- DataCollectionRunSettings.DataCollectors.DataCollector.Configuration.Format=cobertura

      # This saves the test results and code coverage data
    - id: coverage
      name: Code Coverage Report
      uses: irongut/CodeCoverageSummary@v1.3.0
      with:
        filename: PieShopHRM.Tests/TestResults/**/coverage.cobertura.xml
        badge: false
        fail_below_min: false        
        hide_branch_rate: false
        hide_complexity: true
        indicators: true
        output: console

    - id: publish
      name: Publish
      run: dotnet publish "PieShopHRM/PieShopHRM.csproj" -c Release -o ./publish --self-contained -r linux-x64 /p:UseAppHost=true

    - name: Zip Artifact
      run: zip app.zip ./publish

    - id: upload
      name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dotnet-webapp
        path: app.zip


  # Deploy job to deploy the application to Azure

  # Only runs if the build job is successful
  # Downloads the artifact created in the build job
  # Logs into Azure using credentials stored in GitHub Secrets
  # Deploys the application to Azure Web Apps
  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: dotnet-webapp        

    - name: Azure Login
      uses: azure/login@v2
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure
      uses: azure/webapps-deploy@v2
      with:
        app-name: app-pieshophrm
        package: app.zip  
